'use strict';

/**
 * Angielski Daily Trainer 6.6.0
 * Głosowy tryb samochodowy oraz jego ostrzeżenia bezpieczeństwa.
 * Wydzielone z wersji 5.8.3 bez zmiany zachowania aplikacji.
 */

function setCarStatus(text){if($('carStatus'))$('carStatus').textContent=text;}
function clearCarTimer(){if(carAutoTimer){clearTimeout(carAutoTimer);carAutoTimer=null;}}
function stopCarRecognition(){try{if(carRecognition)carRecognition.abort();}catch(_){}carRecognition=null;carCommandMode=false;}
function isCarLessonActive(){return !!(session&&curTask()?.mode==='car_voice'&&!checked&&$('learnScreen')?.classList.contains('active')&&$('lessonCard')?.classList.contains('car-active'));}
function stopCarSession(){stopCarRecognition();clearCarTimer();try{if('speechSynthesis'in window)speechSynthesis.cancel();}catch(_){}pauseSession();}
async function carAskCurrent(){const current=curTask(),word=curWord();if(!current||!word||!isCarLessonActive())return;stopCarRecognition();clearCarTimer();carSilenceRetries=0;setCarStatus('Słuchaj pytania');await speak('Przetłumacz na angielski: '+sentencePl(word),{lang:'pl-PL',repeat:1,rate:.95,force:true});if(!isCarLessonActive())return;setCarStatus('Mów teraz');startCarListening(false);}
async function handleCarNoSpeech(reason='Nie rozpoznano odpowiedzi.'){if(!isCarLessonActive())return;carSilenceRetries++;if(carSilenceRetries<=2){setCarStatus(`Nie usłyszałem. Próba ${carSilenceRetries} z 2.`);await speak('Nie usłyszałem odpowiedzi. Spróbuj jeszcze raz.',{lang:'pl-PL',repeat:1,rate:.95,force:true});if(isCarLessonActive()){setCarStatus('Mów teraz');startCarListening(false);}return;}mark(false,'Brak odpowiedzi',{score:0,status:'wrong',label:'Źle',issues:[{code:'silence',message:reason}],expected:expected(curWord(),'car_voice')});}
function startCarListening(commandOnly=false){const SpeechRecognition=speechApi(),input=document.querySelector('.answer');if(!isCarLessonActive())return;if(!SpeechRecognition){setCarStatus('Brak rozpoznawania mowy w tej przeglądarce');return;}stopCarRecognition();carCommandMode=commandOnly;lastSpeechText='';let failed=false;try{carRecognition=new SpeechRecognition();carRecognition.lang=commandOnly?'pl-PL':(state.settings.voiceLang||'en-US');carRecognition.interimResults=true;carRecognition.continuous=false;carRecognition.onresult=event=>{let text='';for(let index=event.resultIndex;index<event.results.length;index++)text+=event.results[index][0].transcript+' ';lastSpeechText=text.trim();if(input)input.value=lastSpeechText;const box=$('speechTranscript');if(box){box.classList.remove('hidden');box.textContent='Rozpoznano: '+lastSpeechText;}};carRecognition.onerror=event=>{if(!isCarLessonActive())return;failed=true;const code=event.error||'błąd';if(['no-speech','audio-capture'].includes(code))handleCarNoSpeech('Mikrofon nie zarejestrował odpowiedzi.');else setCarStatus('Mikrofon: '+code+'. Użyj przycisku „Mów teraz” albo „Powtórz”.');};carRecognition.onend=()=>{if(!isCarLessonActive()||failed)return;const text=(lastSpeechText||'').trim();if(!text){handleCarNoSpeech();return;}carSilenceRetries=0;if(handleVoiceCommand(text))return;const current=curTask(),word=curWord();if(!current||!word||!isCarLessonActive())return;const result=scoreTaskAnswer(text,word,current.mode);mark(result.status==='correct',text,result);};carRecognition.start();}catch(error){setCarStatus('Nie udało się uruchomić mikrofonu: '+error.message);}}
function handleVoiceCommand(text){const value=normalize(text);if(!value)return false;const has=(...phrases)=>phrases.some(phrase=>value.includes(phrase));if(has('powtorz','powtor','potworz','repeat','again')){handleCarCommand('repeat');return true;}if(has('dalej','dale','daly','next','skip')){handleCarCommand('skip');return true;}if(has('wolniej','slow','slower')){state.settings.voiceRate=clamp((parseFloat(state.settings.voiceRate)||.9)-.1,.5,1.4);syncSettings();save();handleCarCommand('repeat');return true;}if(has('zatrzymaj','zakoncz','koniec','stop','pauza','pause','finish')){handleCarCommand('stop');return true;}if(has('pokaz odpowiedz','pokaż odpowiedź','nie wiem','no idea','show answer')){if(session&&!checked)mark(false,'Nie wiem');return true;}return false;}
function handleCarCommand(command){if(command==='listen'){setCarStatus('Mów teraz');startCarListening(false);return;}if(command==='repeat'){carAskCurrent();return;}if(command==='slower'){state.settings.voiceRate=clamp((parseFloat(state.settings.voiceRate)||.9)-.1,.5,1.4);syncSettings();save();carAskCurrent();return;}if(command==='skip'){if(!session)return;if(checked)nextCard();else mark(false,'Pominięto',{score:0,status:'wrong',label:'Źle',issues:[{code:'skip',message:'Zadanie zostało pominięte.'}],expected:expected(curWord(),curTask()?.mode)});return;}if(command==='stop')stopCarSession();}
async function carAfterMark(ok,word,answer,result=null){stopCarRecognition();clearCarTimer();result=result||scoreTaskAnswer(answer,word,'car_voice');const partial=result.status==='partial';setCarStatus(ok?'Dobrze':partial?'Prawie dobrze':'Do poprawy');const expectedAnswer=result.expected||expected(word,'car_voice');await speak(ok?'Dobrze.':partial?'Prawie dobrze. Posłuchaj poprawnej odpowiedzi.':'Do poprawy. Posłuchaj poprawnej odpowiedzi.',{lang:'pl-PL',repeat:1,rate:.95,force:true});await speak(expectedAnswer,{lang:state.settings.voiceLang||'en-US',repeat:1,rate:Math.max(.65,(parseFloat(state.settings.voiceRate)||.9)-.05),force:true});if(!session||curTask()?.mode!=='car_voice'||!checked||!$('learnScreen')?.classList.contains('active'))return;if(state.settings.carAutoNext!==false){const pause=clamp(parseInt(state.settings.carPause)||3,1,8)*1000;carAutoTimer=setTimeout(()=>{if(session&&checked&&$('learnScreen')?.classList.contains('active'))nextCard();},pause);}}
function showCarWarning(){
  const dialog=$('carWarningDialog');if(!dialog||typeof dialog.showModal!=='function')return Promise.resolve(true);
  if($('carWarningDismiss'))$('carWarningDismiss').checked=false;
  return new Promise(resolve=>{const close=()=>{dialog.removeEventListener('close',close);const allowed=dialog.returnValue==='ok';if(allowed&&$('carWarningDismiss')?.checked){state.settings.carWarningDismissed=true;save();}resolve(allowed);};dialog.addEventListener('close',close);dialog.showModal();});
}
