'use strict';

/**
 * Angielski Daily Trainer 5.8.6
 * Synteza i rozpoznawanie mowy poza trybem samochodowym.
 * Wydzielone z wersji 5.8.3 bez zmiany zachowania aplikacji.
 */

function isCloseEnough(answer,expectedValue){return answerScore(answer,expectedValue).status==='correct';}
function speechApi(){return window.SpeechRecognition||window.webkitSpeechRecognition||null;}
function startSpeechAnswer(){const SpeechRecognition=speechApi(),input=document.querySelector('.answer');if(!input){notify('Brak pola odpowiedzi.','error');return;}if(!SpeechRecognition){$('micStatus')?.classList.remove('hidden');if($('micStatus'))$('micStatus').textContent='Ta przeglądarka nie udostępnia rozpoznawania mowy. Wpisz odpowiedź ręcznie.';return;}try{if(recognition)recognition.abort();recognition=new SpeechRecognition();recognition.lang=state.settings.voiceLang||'en-US';recognition.interimResults=true;recognition.continuous=false;$('micStatus')?.classList.remove('hidden');if($('micStatus'))$('micStatus').textContent='Słucham... powiedz zdanie po angielsku.';recognition.onresult=event=>{let text='';for(let index=event.resultIndex;index<event.results.length;index++)text+=event.results[index][0].transcript+' ';lastSpeechText=text.trim();input.value=lastSpeechText;const box=$('speechTranscript');if(box){box.classList.remove('hidden');box.textContent='Rozpoznano: '+lastSpeechText;}};recognition.onerror=event=>{if($('micStatus'))$('micStatus').textContent='Błąd mikrofonu: '+(event.error||'nieznany')+'. Możesz wpisać odpowiedź ręcznie.';};recognition.onend=()=>{if($('micStatus')?.textContent.startsWith('Słucham'))$('micStatus').textContent=lastSpeechText?'Gotowe. Sprawdź odpowiedź.':'Nie rozpoznano mowy. Spróbuj jeszcze raz albo wpisz ręcznie.';};recognition.start();}catch(error){$('micStatus')?.classList.remove('hidden');if($('micStatus'))$('micStatus').textContent='Nie udało się uruchomić mikrofonu: '+error.message;}}
function isVoiceAllowed(voiceEnabled,force=false){return !!voiceEnabled||!!force;}
function speak(text=null,options={}){const word=curWord();if(!('speechSynthesis'in window)||!isVoiceAllowed(state.settings.voiceEnabled,options.force))return Promise.resolve();const current=curTask(),taskMode=current?.mode||'word_write',message=text||((taskMode==='speaker_repeat'&&state.settings.preferExample!==false)?sentenceEn(word):expected(word,taskMode));if(!message)return Promise.resolve();speechSynthesis.cancel();const voices=speechSynthesis.getVoices(),language=options.lang||state.settings.voiceLang||'en-US',base=language.split('-')[0].toLowerCase(),selected=voices.find(voice=>voice.name===state.settings.voiceName),selectedMatches=selected&&String(selected.lang||'').toLowerCase().startsWith(base),chosen=(selectedMatches?selected:null)||voices.find(voice=>voice.lang===language)||voices.find(voice=>String(voice.lang||'').toLowerCase().startsWith(base)),repeat=clamp(parseInt(options.repeat??state.settings.voiceRepeat)||1,1,4),rate=clamp(parseFloat(options.rate??state.settings.voiceRate)||.9,.5,1.4);return new Promise(resolve=>{let left=repeat;const run=()=>{const utterance=new SpeechSynthesisUtterance(message);utterance.lang=language;utterance.rate=rate;if(chosen)utterance.voice=chosen;utterance.onend=()=>{left--;left>0?run():resolve();};utterance.onerror=()=>resolve();speechSynthesis.speak(utterance);};run();});}
