'use strict';

/**
 * Angielski Daily Trainer 6.6.0
 * Ekrany statystyk, postępu, materiałów i planu dnia.
 * Wydzielone z wersji 5.8.3 bez zmiany zachowania aplikacji.
 */

function renderAll(){renderToday();renderReviews();renderCourseUi();renderProgress();renderBase();}
function renderTopMetrics(){if($('topXp'))$('topXp').textContent=state.user.xp;if($('topStreak'))$('topStreak').textContent=state.user.streakDays;}
function renderToday(){
  renderTopMetrics();
  const tasks=queue(false),dueCount=due().length,today=state.days[todayKey()]||{correct:0,wrong:0},done=(today.correct||0)+(today.wrong||0),goal=state.settings.dailyGoal||20;
  if($('goalText'))$('goalText').textContent=`${Math.min(done,goal)} z ${goal} zadań`;setProgress($('goalBar'),Math.round(done/Math.max(goal,1)*100));
  if($('queueBadge'))$('queueBadge').textContent=tasks.length+' zadań';if($('queueList'))$('queueList').innerHTML=tasks.slice(0,10).map(itemData=>item(WORDS.find(word=>word.id===itemData.wordId),itemData)).join('')||'<p class="muted">Brak zadań według bieżących ustawień.</p>';
  if($('homeReviewCount'))$('homeReviewCount').textContent=dueCount;
  if($('homeReviewText'))$('homeReviewText').textContent=dueCount?`Masz ${dueCount} ${dueCount===1?'materiał':'materiały'} zaplanowane do powtórki.`:'Brak zaległego materiału. Możesz przejść do kursu albo treningu.';
  if($('homeReviewBtn'))$('homeReviewBtn').disabled=dueCount===0;
  if($('homeTrainingKnownCount'))$('homeTrainingKnownCount').textContent=courseKnownMaterialIds().length;
  const resume=$('resumeCard');if(resume){const saved=state.activeSession,valid=saved&&Array.isArray(saved.queue)&&saved.index<=saved.queue.length;resume.classList.toggle('hidden',!valid);if(valid&&$('resumeInfo')){const prefix=saved.source==='course'&&saved.lessonTitle?`${saved.lessonTitle} · `:'';$('resumeInfo').textContent=saved.index===saved.queue.length?`${prefix}sesja ukończona • poprawne: ${saved.correct||0}. Otwórz podsumowanie.`:`${prefix}zadanie ${saved.index+1} z ${saved.queue.length} • poprawne: ${saved.correct||0}.`;}}
}
function item(word,taskData){if(!word)return'';return `<div class="item"><div><strong>${esc(word.english)}</strong><div class="muted">${esc(word.polish)}</div><div class="minirow"><span class="mini">${esc(word.level)}</span><span class="mini">${esc(word.track)}</span><span class="mini amber">${esc(taskData.kind==='weak'?'do powtórki':taskData.kind==='new'?'nowe':'powtórka')}</span></div></div><span class="badge">${prog(word.id).mastery}%</span></div>`;}
function wordItem(word){const progress=prog(word.id),statusClass=progress.status==='mastered'?'green':progress.status==='weak'?'red':'amber',g=word.grammar||{},grammar=g.partOfSpeech||word.partOfSpeech||'',meaning=Array.isArray(word.meanings)&&word.meanings.length>1?`Inne znaczenie: ${word.meanings.slice(1).map(item=>item.pl||item).join(', ')}`:'',example=word.examples?.[0]?.en&&hasQualityExample(word)?`Przykład: ${word.examples[0].en}`:'',forms=[g.plural&&g.plural!=='—'?`lm. ${g.plural}`:'',g.past?`Past: ${g.past}`:'',g.pastParticiple?`PP: ${g.pastParticiple}`:'',g.typicalPrepositions?`przyimki: ${g.typicalPrepositions}`:'',g.structure?`konstrukcja: ${g.structure}`:''].filter(Boolean).join(' • '),collocations=word.collocations?.length?`Połączenia: ${word.collocations.join(', ')}`:'',mistakes=word.commonMistakes?.length?`Uwaga: ${word.commonMistakes[0]}`:'';return `<div class="item"><div><strong>${esc(word.english)}</strong><div class="muted">${esc(word.polish)}</div><div class="minirow"><span class="mini">${esc(word.level)}</span><span class="mini">${esc(word.track)}</span>${word.specialism?`<span class="mini">${esc(word.specialism)}</span>`:''}${grammar?`<span class="mini">${esc(grammar)}</span>`:''}<span class="mini ${statusClass}">${esc(status(progress.status))}</span></div>${[example,forms,collocations,meaning,mistakes].filter(Boolean).map(text=>`<div class="material-extra">${esc(text)}</div>`).join('')}</div><span class="badge">${progress.mastery}%</span></div>`;}
function renderReviews(){const list=[...due(),...weak()].filter((word,index,array)=>array.findIndex(item=>item.id===word.id)===index).slice(0,60);if($('reviewsList'))$('reviewsList').innerHTML=list.map(wordItem).join('')||'<p class="muted">Brak zaległych powtórek.</p>';}
function renderProgress(){const progresses=WORDS.map(word=>prog(word.id));if($('mastered'))$('mastered').textContent=progresses.filter(progress=>progress.status==='mastered').length;if($('learning'))$('learning').textContent=progresses.filter(progress=>progress.seen>0&&progress.status!=='mastered'&&progress.status!=='weak').length;if($('weak'))$('weak').textContent=progresses.filter(progress=>progress.status==='weak').length;if($('bestStreak'))$('bestStreak').textContent=state.user.bestAnswerStreak;if($('statXp'))$('statXp').textContent=state.user.xp;if($('statLevel'))$('statLevel').textContent='Poziom '+state.user.level;if($('statStreak'))$('statStreak').textContent=state.user.streakDays+' dni';if($('statAcc'))$('statAcc').textContent=percent(state.user.totalCorrect,state.user.totalCorrect+state.user.totalWrong);const mostMistakes=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id])=>WORDS.find(word=>word.id===id)).filter(Boolean);if($('mistakes'))$('mistakes').innerHTML=mostMistakes.map(wordItem).join('')||'<p class="muted">Brak błędów.</p>';renderModeStats();renderHistory14();}
function widthClass(value){return'w-'+clamp(Math.round(Number(value)/5)*5,0,100);}
function setProgress(element,value){if(!element)return;element.setAttribute?.('role','progressbar');element.setAttribute?.('aria-valuemin','0');element.setAttribute?.('aria-valuemax','100');for(let width=0;width<=100;width+=5)element.classList.remove('w-'+width);element.classList.add(widthClass(value));element.setAttribute?.('aria-valuenow',String(clamp(Math.round(value),0,100)));}
function renderModeStats(){const labels={course_final:'zadanie końcowe',course_intro:'wprowadzenie',word_choice:'wybór',word_write:'pisanie',sentence_translate:'zdania',listening_write:'słuchanie',speaker_repeat:'lektor',speaking:'mówienie',dialogue:'dialog',car_voice:'samochód'};const entries=Object.entries(state.modeStats||{});if($('modeStats'))$('modeStats').innerHTML=entries.length?entries.map(([key,value])=>{const total=(value.correct||0)+(value.wrong||0),accuracy=total?Math.round((value.correct||0)/total*100):0;return `<div><div class="barline"><strong>${esc(labels[key]||key)}</strong><div class="bartrack"><div class="barfill ${widthClass(accuracy)}" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${accuracy}" aria-label="Skuteczność ${esc(labels[key]||key)}"></div></div><span class="badge">${accuracy}%</span></div><div class="muted">${total} odpowiedzi, XP: ${value.xp||0}</div></div>`;}).join(''):'<p class="muted">Brak danych z trybów. Zrób jedną sesję.</p>';}
function renderHistory14(){const days=[];for(let index=13;index>=0;index--)days.push(addDays(-index));if($('history14'))$('history14').innerHTML=days.map(day=>{const entry=state.days[day]||{correct:0,wrong:0,xp:0},total=(entry.correct||0)+(entry.wrong||0);return `<div class="daybox"><strong>${day.slice(5)}</strong><span>${total} odp.</span><span>${entry.xp||0} XP</span></div>`;}).join('');}
function renderBase(){if(!$('baseList'))return;const query=normalize($('searchInput')?.value||''),level=$('levelFilter')?.value||'all',track=$('trackFilter')?.value||'all';const filtered=WORDS.filter(word=>(level==='all'||word.level===level)&&(track==='all'||word.track===track)&&(!query||normalize(`${word.english} ${word.polish} ${word.category} ${word.examples?.[0]?.en||''}`).includes(query)));if($('baseCount'))$('baseCount').textContent=filtered.length+' / '+WORDS.length;$('baseList').innerHTML=filtered.slice(0,240).map(wordItem).join('')||'<p class="muted">Nic nie znaleziono.</p>';}
function status(value){return {new:'nowe',review:'w nauce',weak:'do powtórki',mastered:'opanowane'}[value]||value;}
